import os
# Constants
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800
SCREEN_TITLE = "Astro Flight"
SCALING = 1.0
ASTEROID_SCALING = [0.5, 0.3, 0.8] 
BUTTON_SCALING = 0.5
LIVES = 3
LIVES_SCALING = 2.0
LIVES_POSITIONS = [40, 110, 180]
PATH = os.path.dirname(os.path.abspath(__file__))
TROPHY_SCALING = 0.6